stages:
  - test
  - pack
  - deploy

variables:
  INSTALL_PACKAGES: git gcc make cmake unzip python36-pip
  BUNDLE_VERSION: 1.10.3-68-g618f48d
  PACKAGE_TARGETS: |
    OS=el DIST=6
  PACKAGECLOUD_REPOS: |
    1_10
    2x
    2_2

.job: &job
  image: centos:7
  tags:
    - docker
    - mcs

pack:
  <<: *job
  stage: pack
  when: manual
  tags:
    - molecule-dind
  image: docker:git
  services:
    - name: docker:dind
      alias: localhost
  variables:
    PRODUCT: cartridge-cli
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  before_script:
    - git describe --long
  script:
    - (set -ex;
      echo "$PACKAGE_TARGETS" | while read -r vars; do (
        [ -z "$vars" ] && exit;
        export $vars;
        BUILDDIR=`pwd`/build/$OS/$DIST packpack/packpack;
      ) done)
    - ls -l build/**/*
  artifacts:
    expire_in: 12h
    paths:
      - build/

deploy:
  <<: *job
  stage: deploy
  when: manual
  image:
    name: digitalocean/packagecloud
    entrypoint: ['']
  script:
    - (set -ex;
      echo "$PACKAGE_TARGETS" | while read -r vars; do (
        [ -z "$vars" ] && exit;
        export $vars;
        for ext in deb rpm; do (
          [ -z "$(ls build/$OS/$DIST/*.$ext 2> /dev/null)" ] && exit;
          echo "$PACKAGECLOUD_REPOS" | while read -r repo; do (
            [ -z "$repo" ] && exit;
            package_cloud push $PACKAGECLOUD_USER/$repo/$OS/$DIST build/$OS/$DIST/*.$ext;
          ) done;
        ) done;
      ) done)
